[package]
name = "calendar_bot"
version = "0.1.0"
authors = ["Erik Johnston <cargo@jki.re>"]
edition = "2018"

[dependencies]
ics_parser = { git = "https://github.com/erikjohnston/ics_parser", branch = "main" }
reqwest = { version = "0.11.0", features = ["json"] }
tokio = { version = "1.2", features = ["full"] }
anyhow = "1.0.38"
chrono = "0.4.19"
roxmltree = "0.14.0"
tokio-postgres ={ version = "0.7.0", features = ["with-chrono-0_4"] }
futures = "0.3.12"
bb8-postgres = "0.7.0"
bb8 = "0.7.0"
serde = { version = "1.0.123", features = ["derive"] }
toml = "0.5.8"
clap = "2.33.3"
tracing = "0.1.23"
tracing-subscriber = "0.2.15"
serde_json = "1.0.62"
handlebars = "3.5.2"
comrak = "0.9.1"
actix-web = "4.0.0-beta.5"
postgres-types = { version = "0.2.0", features = ["derive"] }
itertools = "0.10.0"
tracing-actix-web = "0.4.0-beta.4"
tera = "1.6.1"
bcrypt = "0.9.0"
rand = "0.8.3"
time = "0.2.25"
urlencoding = "1.1.1"
url = "2.2.2"

[profile.release]
debug = true

[patch.crates-io]
tokio-postgres = { git = "https://github.com/sfackler/rust-postgres", rev = "d95eb353dd0fccec5986cb364d6bd1ef10034fac" }
postgres-types = { git = "https://github.com/sfackler/rust-postgres", rev = "d95eb353dd0fccec5986cb364d6bd1ef10034fac" }
